name: updated
description: Managing state of asynchronous updates as a simple dart representation.
version: 0.1.9
homepage: https://github.com/aloisdeniel/updated

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  meta: ^1.2.4

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
